types = ['german', 'japanese', 'vegetarian', 'french', 'african', 'american', 'barbecue', 'czech', 'chinese', 'thai',
         'mexican', 'indian', 'cafe', 'pizza', 'italian', 'seafood']

restaurant_data = [['german', "The Malted Barley", '5', '5', '334 Westminster St.'],
                   ['japanese', 'O Sushi Restaurant and Bar','4', '5', '7659 Post Rd.'],
                   ['vegetarian', 'Plant City', '4', '4', '334 S Water St.'],
                   ['french', 'Rue Bris', '5', '4', '95 South St.'],
                   ['african', 'Abinchin Plateau', '4', '3', '65 Bath St.'],
                   ['american', "CAV Restaurant", '5', '5', '14 Imperial Pl.'],
                   ['barbecue', 'Oak Hill Tavern & BBQ', '4', '4', '565 Tower Hill Rd.'],
                   ['czech', 'Cafe Polonia', '4', '4', '611 Dorchester Ave.'],
                   ['german', 'Munich Haus', '3', '4', '13 Center Street'],
                   ['chinese', "Jacky's Galaxie and Sushi Bar", '4', '4', '1488 Mineral Spring Ave.'],
                   ['thai', 'Green Basil', '5', '4', '2086 Mineral Spring Ave.'],
                   ['mexican', "Tallulah's Taqueria", '4', '5', '146 Ives St.'],
                   ['indian', 'Rasoi Restaurant', '4', '4', '727 East Ave.'],
                   ['italian', 'Camilles', '4', '5', '71 Bradford St.'],
                   ['american', 'Nicks on Broadway', '4', '4', '500 Broadway'],
                   ['barbecue', 'Great Northern BBQ Co.', '4', '4', '9 Parade St.'],
                   ['seafood', 'Hemenways Restaurant', '4', '5', '121 S Main St.'],
                   ['seafood', 'Matunuk Oyster Bar', '3', '5', '629 Succotash Rd.'],
                   ['chinese', "Lemongrass", '2', '4', '1138 Post Road'],
                   ['thai', 'Thai Star Go', '3', '5', '895 Smith St.'],
                   ['mexican', 'On The Border', '2', '4', '650 Bald Hill Rd.'],
                   ['indian', 'Kabob and Curry', '3', '4', '261 Thayer St.'],
                   ['mexican', 'Condesa Restaurante Mexicano', '3', '4', '970 Douglas Pike'],
                   ['italian', "Luigi's Restaurant", '3', '4', '1357 Hartford Ave.'],
                   ['chinese', 'Super Wonton Express', '2', '1', '223 Milliways Ave'],
                   ['french', 'POT AU FEU', '4', '4', '44 Custom House St.'],
                   ['japanese', 'Wara Wara Restaurant', '3', '5', '776 Hope St.'],
                   ['barbecue', "DURK'S BAR-B-Q", '3', '4', '33 Aborn Street'],
                   ['vegetarian', 'Garden Grille', '3', '5', '727 East Ave'],
                   ['cafe', 'Small Point Cafe', '1', '4', '230 Westminster St.'],
                   ['cafe', 'Brewgrindz Coffee Shop', '4', '5', '1775 Mineral Spring Ave.'],
                   ['cafe', "Coffee Exchange", '2', '5', '207 Wickenden St.'],
                   ['cafe', 'Zardoz Cafe', '4', '2', '6202 Alameda'],
                   ['pizza', 'Twins Pizza', '5', '5', '1000 Mineral Spring Ave.'],
                   ['pizza', "Big Tony's Pizza", '4', '4', '525 Eaton Street'],
                   ['pizza', "Rosa Mia Pizza", '2', '4', '133 Greenville Ave.'],
                   ['vegetarian', 'PiANTA Vegan Restaurant', '4', '5', '408 Atwells Ave.'],
                   ['indian', 'India Restaurant', '4', '5', '1060 Hope St.'],
                   ['pizza', 'Pizza 76', '4', '3', '76 Market St.'],
                   ['italian', 'Massimo Ristorante', '5', '5', '134 Atwells Ave.']]