genres = ['platformer', 'role-playing game', 'shooter', 'puzzle', 'action', 'adventure', 'racing', 
         'fighting', 'batte royale', 'survival', 'sports', 'rhythm', 'horror', 'hack and slash', 'sandbox']

# game_data =  [[(genre), (game name), (developer), (system), (release year)]]


game_data = [['platformer', "Super Mario Galaxy", 'Nintendo', 'Nintendo Wii', '2007'], 
             ['horror', "Resident Evil 4 Remake", 'Capcom', 'Playstation 5', '2023'], 
             ['role-playing game', "Final Fantasy VII", "SquareEnix", "Playstation", "1997"], 
             ['shooter', "Halo Infinite", '343 Industries', 'Xbox Series X', '2021'],
             ['puzzle', "Portal 2", 'Valve', 'Xbox 360', '2011'],
             ['action', "God of War Ragnarök", 'Santa Monica Studios', 'Playstation 5', '2022'],
             ['adventure', "The Legend of Zelda: Breath of the Wild", 'Nintendo', 'Nintendo Switch', '2017'],
             ['racing', "Forza Horizon 5", 'Playground Games', 'Xbox Series X', '2021'],
             ['fighting', "Super Smash Bros. Ultimate", 'Nintendo', 'Nintendo Switch', '2018'],
             ['battle royale', "Fortnite Battle Royale", 'Epic Games', 'Windows', '2017'],
             ['survival', "Subnautica: Below Zero", 'Unknown Worlds', 'Windows', '2021'],
             ['sports', "Madden NFL 24", 'EA Sports', 'EA Tiburon', 'Playstation 5', '2023'],
             ['rhythm', "Rhythm Heaven Megamix", 'Nintendo', 'Nintendo 3DS', '2015'],
             ['hack and slash', "Devil May Cry 5", 'Capcom', 'Playstation 5', '2019'],
             ['sandbox', "Minecraft", 'Mojang Studios', 'Windows', '2011'],
             ['platformer', "Crash Bandicoot: Warped", "Naughty Dog", "Playstation", '1998'],
             ['horror', "Silent Hill 2", 'Team Silent', 'Playstation 2', '2001'],
             ['role-playing game', "Xenoblade Chronicles 3", 'Monolith Soft', 'Nintendo Switch', '2022'],
             ['shooter', "Splatoon 2", 'Nintendo EPD', 'Nintendo Switch', '2017'],
             ['puzzle', "Braid", 'Number None', 'Xbox 360', '2008'],
             ['action', "Marvel's Spider-Man", 'Insomniac Games', 'Playstation 4', '2018'],
             ['adventure', "Hogwarts Legacy", 'Avalanche Software', 'Playstation 5', '2023'],
             ['racing', "Mario Kart Double Dash", 'Nintendo EAD', 'Nintendo GameCube', '2003'],
             ['fighting', "Super Street Fighter II Turbo", 'Capcom', 'Arcade', '1994'],
             ['battle royale', "Apex Legends", 'Respawn Entertainment', 'Windows', '2019'],
             ['survival', "No Man's Sky", 'Hello Games', 'Playstation 4', '2016'],
             ['sports', "MLB The Show 23", 'San Diego Studios', 'Playstation 4', '2023'],
             ['rhythm', "Theatrhythm Final Fantasy", 'indieszero', 'Nintendo 3DS', '2012'],
             ['hack and slash', "Bayonetta 2", 'Platinum Games', 'Nintendo Wii U', '2014'],
             ['sandbox', "Terraria", 'Re-Logic', 'Windows', '2011'],
             ['platformer', "Sonic Unleashed", 'Sonic Team', 'Xbox 360', '2008'],
             ['horror', "Five Nights at Freddy's", 'Scott Cawthon', 'Windows', '2014'],
             ['role-playing game', "Dragon Quest V: Hand of the Heavenly Bride", 'ArtePiazza', 'Nintendo DS', '2009'],
             ['shooter', "Call of Duty 4: Modern Warfare", 'Infinity Ward', 'Windows', '2007'],
             ['puzzle', "Puyo Puyo Tetris", 'Sonic Team', 'Nintendo Switch', '2017'],
             ['action', "The Last of Us Part II", 'Naughty Dog', 'Playstation 4', '2020'],
             ['adventure', "Red Dead Redemption 2", 'Rockstar Games', 'Xbox One', '2018'],
             ['racing', "F-Zero GX", 'Amusement Vision', 'Nintendo GameCube', '2003'],
             ['fighting', "Dragon Ball FighterZ", 'Arc System Works', 'Playstation 4', '2018'],
             ['battle royale', "Fall Guys", 'Mediatonic', 'Windows', '2020'],
             ['survival', "Grounded", 'Obsidian Entertainment', 'Xbox One', '2022'],
             ['sports',  "NBA 2K22", 'Visual Concepts', 'Playstation 4', '2021'],
             ['rhythm', "Dance Dance Revolution: Mario Mix", 'Konami', 'Nintendo GameCube', '2005'],
             ['hack and slash', "Hyrule Warriors", 'Omega Force', 'Nintendo Wii U', '2014'],
             ['sandbox', "Garry's Mod", 'Facepunch Studios', 'Windows', '2006']]